org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=23
unityProjectPath=C:/ProParcel/mobile/mobil_github/unity/vrParcel
unity.projectPath=C:/ProParcel/mobile/mobil_github/unity/vrParcel
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.1.0
unity.minSdkVersion=25
unity.targetSdkVersion=36
unity.compileSdkVersion=36
unity.applicationId=com.DefaultCompany.proparcel
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=0.1
unity.namespace=com.DefaultCompany.proparcel
unity.agpVersion=9.0.0
unity.androidSdkPath=C:/Android/Sdk
unity.androidNdkPath=C:/Android/Sdk/ndk/27.2.12479018
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Eclipse Adoptium/jdk-17.0.17.10-hotspot
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never